### ISSUE TITLE
xlsx to pdf conversion does not retain word wrapping settings

### ISSUE THREAD

**Issue by deantaylormax** [zamzar/zamzar-samples-hotfolders#2]
Now, this may not be your code, but may be the zamzar API.  But, I have a formatted xlsx file that includes wrapping on column text and when the conversion to pdf is complete, the column text content is cutoff instead of wrapped.  However, the column width settings of the xlsx are preserved in the converted pdf.  I presume it is not your code causing this, but just in case i thought I would bring this to your attention.  My Python is intermediate level at the moment so that may be my mistake.

**Comment by whyleyc** [comment]
Thanks for reporting this @johntaylorpa  - this issue is present regardless of what client code is used, so isn't an issue specific to the way the API is called, but rather with the internal API file processing. We've raised it as an issue internally.
